language: python
python:
 - '3.4'
 - '3.5'
 - '3.6'
before_install:
 - pip3 install cython
script:
 - pip3 install .
 - cd ..; python3 -c "import pybus"
 - export DBUS_LAUNCHD_SESSION_BUS_SOCKET=./dbus-sock
 - dbus-daemon --session --address unix:path=$DBUS_LAUNCHD_SESSION_BUS_SOCKET --fork
 - python3 ./pybus/demo_client.py
