language: python
python:
 - '3.5'
 - '3.6'
before_install:
 - pip3 install cython
 - sudo apt-get install -y dbus
script:
 - pip3 install .
 - cd ..; python3 -c "import debus"
 - export DBUS_SESSION_BUS_SOCKET=unix:path=./dbus-sock
 - dbus-daemon --session --address $DBUS_SESSION_BUS_SOCKET --fork
 - python3 ./debus/bin/demo_client.py
